export const ErrorMessage = {
  USER_EXIST: 'User already exist!',
  USER_NOT_FOUND: 'User does not exist!',
  USER_NOT_CREATE: 'Error while creating user!',
  USER_NOT_UPDATED: 'Error while updateting user!',
  USER_RECORDS_NOT_FOUND: 'No user records found!',
  USER_ABOUT_NOT_FOUND: 'User about data does not exist!',
  USER_ABOUT_NOT_CREATE: 'Error while creating user about!',
  USER_ABOUT_NOT_UPDATED: 'Error while updateting user about!',
  USER_ABOUT_RECORDS_NOT_FOUND: 'No user about records found!',
  USER_SKILL_NOT_FOUND: 'User skill data does not exist!',
  USER_SKILL_NOT_CREATE: 'Error while creating user skill!',
  USER_SKILL_NOT_UPDATED: 'Error while updateting user skill!',
  USER_RESUME_NOT_FOUND: 'User resume data does not exist!',
  USER_RESUME_NOT_CREATE: 'Error while creating user resume !',
  USER_RESUME_NOT_UPDATED: 'Error while updateting user resume!',
  USER_RESUME_NOT_DELETED: 'Error while deleting user resume!',
  USER_SERVICE_NOT_FOUND: 'User service data does not exist!',
  USER_SERVICE_NOT_CREATE: 'Error while creating user service!',
  USER_SERVICE_NOT_UPDATED: 'Error while updateting user service!',
  USER_PROJECT_NOT_FOUND: 'User project data does not exist!',
  USER_PROJECT_NOT_CREATE: 'Error while creating user project!',
  USER_PROJECT_NOT_UPDATED: 'Error while updateting user project!',
  USER_PROJECT_NOT_DELETED: 'Error while deleting user project!',
  INVALID_CREDENTIALS: 'Invalid email or password!',
  INVALID_TOKEN: 'The token is invalid!',
  EXPIRED_TOKEN: 'Token expired!',
  REVOKE_TOKEN: 'Token is invalid or has been revoked',
  UNAUTHORIZED_ACCESS: 'Unauthorized access!',
  INVALID_ID: 'Please provide valid ID!',
  PASSWORD_CHANGE_NOT_ALLOWED: 'You can not directly change password',
  EMAIL_CHANGE_NOT_ALLOWED: 'You can not directly change email',
};

export const DTOErrorMessage = {
  INVALID_EMAIL: 'Please enter a valid email address.',
  INVALID_PASSWORD:
    'Password must contain at least one uppercase letter, one number, and one special character',
  AT_LEAST_ONE_SOCIAL_MEDIA: 'At least one social media is required',
};
